#ifndef NORTHPOLE_GATT_H
#define NORTHPOLE_GATT_H

#ifdef __cplusplus
extern "C" {
#endif

#define NORTHPOLE_DIAG_SERVICE_UUID      0xFD90
#define NORTHPOLE_DIAG_VERSION_UUID      0xFD91
#define NORTHPOLE_DIAG_BOARD_UUID        0xFD92
#define NORTHPOLE_DIAG_STATUS_UUID       0xFD93
#define NORTHPOLE_DIAG_COUNTERS_UUID     0xFD94
#define NORTHPOLE_DIAG_CONTROL_UUID      0xFD95
#define NORTHPOLE_DIAG_PROFILE_UUID      0xFD96

#define NORTHPOLE_DIAG_CONTROL_RGB_ALL       0x01u
#define NORTHPOLE_DIAG_CONTROL_CLEAR_FAULTS  0x02u
#define NORTHPOLE_DIAG_CONTROL_AUDIO_STOP    0x03u
#define NORTHPOLE_DIAG_CONTROL_AUDIO_PLAY_INDEX 0x04u
#define NORTHPOLE_DIAG_CONTROL_AUDIO_VOLUME  0x05u
#define NORTHPOLE_DIAG_CONTROL_AUDIO_PAUSE   0x06u
#define NORTHPOLE_DIAG_CONTROL_AUDIO_QSTATUS 0x07u

#define NORTHPOLE_DIAG_CONTROL_AUDIO_PLAY NORTHPOLE_DIAG_CONTROL_AUDIO_PLAY_INDEX

extern bStatus_t NorthPoleDiag_AddService(void);

#ifdef __cplusplus
}
#endif

#endif /* NORTHPOLE_GATT_H */
