#ifndef BUILD_PROFILE_H
#define BUILD_PROFILE_H

typedef enum {
    BUILD_PROFILE_ID_BRINGUP = 0,
    BUILD_PROFILE_ID_PRODUCTION = 1,
} build_profile_t;

#define BUILD_PROFILE_BRINGUP 0
#define BUILD_PROFILE_PRODUCTION 1

#if defined(FIRMWARE_PROFILE_PRODUCTION)
#define BUILD_PROFILE BUILD_PROFILE_PRODUCTION
#define BUILD_PROFILE_NAME "production"
#else
#define FIRMWARE_PROFILE_BRINGUP 1
#define BUILD_PROFILE BUILD_PROFILE_BRINGUP
#define BUILD_PROFILE_NAME "bringup"
#endif

#endif /* BUILD_PROFILE_H */
